// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrqqeidpzmmaprxpfvwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycXFlaWRwem1tYXByeHBmdndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzgzMTYsImV4cCI6MjA1ODExNDMxNn0.Z-1w4EaGOMarMTCVowy_SqBRzfW8n1FioDY-etauSfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);